/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutCacheRouteImport } from './routes/_layout/cache'
import { Route as LayoutFullSsrRouteImport } from './routes/_layout/full-ssr'
import { Route as LayoutLoadingRouteImport } from './routes/_layout/loading'
import { Route as LayoutPolishRouteImport } from './routes/_layout/polish'
import { Route as LayoutSsrWithModalRouteImport } from './routes/_layout/ssr-with-modal'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCacheRoute = LayoutCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFullSsrRoute = LayoutFullSsrRouteImport.update({
  id: '/full-ssr',
  path: '/full-ssr',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoadingRoute = LayoutLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPolishRoute = LayoutPolishRouteImport.update({
  id: '/polish',
  path: '/polish',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSsrWithModalRoute = LayoutSsrWithModalRouteImport.update({
  id: '/ssr-with-modal',
  path: '/ssr-with-modal',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/cache': typeof LayoutCacheRoute
  '/full-ssr': typeof LayoutFullSsrRoute
  '/loading': typeof LayoutLoadingRoute
  '/polish': typeof LayoutPolishRoute
  '/ssr-with-modal': typeof LayoutSsrWithModalRoute
}
export interface FileRoutesByTo {
  '/cache': typeof LayoutCacheRoute
  '/full-ssr': typeof LayoutFullSsrRoute
  '/loading': typeof LayoutLoadingRoute
  '/polish': typeof LayoutPolishRoute
  '/ssr-with-modal': typeof LayoutSsrWithModalRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/cache': typeof LayoutCacheRoute
  '/_layout/full-ssr': typeof LayoutFullSsrRoute
  '/_layout/loading': typeof LayoutLoadingRoute
  '/_layout/polish': typeof LayoutPolishRoute
  '/_layout/ssr-with-modal': typeof LayoutSsrWithModalRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cache' | '/full-ssr' | '/loading' | '/polish' | '/ssr-with-modal'
  fileRoutesByTo: FileRoutesByTo
  to: '/cache' | '/full-ssr' | '/loading' | '/polish' | '/ssr-with-modal' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/cache'
    | '/_layout/full-ssr'
    | '/_layout/loading'
    | '/_layout/polish'
    | '/_layout/ssr-with-modal'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cache': {
      id: '/_layout/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof LayoutCacheRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/full-ssr': {
      id: '/_layout/full-ssr'
      path: '/full-ssr'
      fullPath: '/full-ssr'
      preLoaderRoute: typeof LayoutFullSsrRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/loading': {
      id: '/_layout/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LayoutLoadingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/polish': {
      id: '/_layout/polish'
      path: '/polish'
      fullPath: '/polish'
      preLoaderRoute: typeof LayoutPolishRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ssr-with-modal': {
      id: '/_layout/ssr-with-modal'
      path: '/ssr-with-modal'
      fullPath: '/ssr-with-modal'
      preLoaderRoute: typeof LayoutSsrWithModalRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCacheRoute: typeof LayoutCacheRoute
  LayoutFullSsrRoute: typeof LayoutFullSsrRoute
  LayoutLoadingRoute: typeof LayoutLoadingRoute
  LayoutPolishRoute: typeof LayoutPolishRoute
  LayoutSsrWithModalRoute: typeof LayoutSsrWithModalRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCacheRoute: LayoutCacheRoute,
  LayoutFullSsrRoute: LayoutFullSsrRoute,
  LayoutLoadingRoute: LayoutLoadingRoute,
  LayoutPolishRoute: LayoutPolishRoute,
  LayoutSsrWithModalRoute: LayoutSsrWithModalRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
